### ISSUE TITLE
DeleteFromQuery failes with DateTime parameter

### ISSUE THREAD

**Issue by LukeOrdelmans** [NorthernLight1/N.EntityFramework.Extensions#54]
query 
```
DateTime deleteBeforeDate = DateTime.Now.AddDays(-NumberOfDays);
var query = context.Jobs.Where(j =>j.Date != null && j.Date < deleteBeforeDate);
query.DeleteFromQuery();
```

throws exception: **Must declare the scalar variable \"@p__linq__0\".**

if I inspect the query object via the debugger I can see that the p__linq__0 parameter is available with name, type and value

database is **Sql Server**
column type is **datetime**

**Comment by NorthernLight1** [comment]
LukeOrdelmans,

I have a patch coming this weekend that will fix this issue for DeleteFromQuery, InsertFromQuery and UpdateFromQuery. 

There was a test case for UpdateFromQuery that checked for a datetime parameter, but since it was only looking for NULL and not an actual value, it behaved a little different. It had the same exact issue that you reported, so I made sure to update the test to cover it.

**Comment by NorthernLight1** [comment]
LukeOrdelmans,

I have fixed the issue you mentioned above and pushed a new version to Nuget (v1.5.2). Please test it out and let me know if you find any other issues with the framework.

**Comment by LukeOrdelmans** [comment]
Yes, works like a charms now :thumbsup:, thanks!
